### ISSUE TITLE
RestfulService - Put Method returns "302 Found" status, shoud be "200 Success"

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-restfulserver#10]
Reported by hamish, migrated from http://open.silverstripe.org/ticket/3532

A successful PUT command (update DataObject?) returns status code 302. This should return 200 on success.

Line 372 appears to be the cause:

$this->getResponse()->addHeader('Location', $objHref);
Commenting this line out produces 200 status codes. Surely the location should already by $objHref, since that is the required address for the put request in the first place.

**Comment by robbieaverill** [comment]
A temporary redirect doesn't seem relevant at all. There are cases where a 301 may be used to indicate an undesirable API request path, pointing to the desired path instead.

[See here](http://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html#sec9.6) - implies generally that 20x headers should be used.

+1 from me.

**Comment by tractorcow** [comment]
Would you be able to put up a pull request for this? You can probably manually set response code to 201 on create, after setting `Location` header (or 200 if that's what the correct response is).

**Comment by dhensby** [comment]
Reading [the latest RFC](https://tools.ietf.org/html/rfc7231#section-4.3.4) and it states:

> If the target resource does not have a current representation and the PUT successfully creates one, then the origin server MUST inform the user agent by sending a 201 (Created) response.  If the target resource does have a current representation and that representation is successfully modified in accordance with the state of the enclosed representation, then the origin server MUST send either a 200 (OK) or a 204 (No Content) response to indicate successful completion of the request.

So it should return 201 if it's new and a 200 (or 204) if it's edited

**Comment by robbieaverill** [comment]
I think this has been fixed.

`putHandler` updates a record and sets a 200 (OK) header on completion:

```
$ curl -XPUT --verbose http://admin:admin@cwp17.dev/api/v1/HomePage/1 -H 'Content-Type: application/json' -d '{"Title": "Testing"}'
...
< HTTP/1.1 200 OK
< Date: Fri, 17 Nov 2017 03:43:54 GMT
...
```

`postHandler` creates a record and sets a 201 (Created) header:

```
$ curl --verbose http://admin:admin@cwp17.dev/api/v1/HomePage/ -H 'Content-Type: application/json' -d '{"Title": "Testing"}'
...
< HTTP/1.1 201 Created
< Date: Fri, 17 Nov 2017 03:46:30 GMT
...
```
