### ISSUE TITLE
getHandler() error when calling a method

### ISSUE THREAD

**Issue by KINKCreative** [silverstripe/silverstripe-restfulserver#16]
When calling a method via GET or POST e.g.

api/v1/DataObject/ID/methodName

getObjectRelationQuery() checks if the relation exists. Because it does not, it throws an error: method dataClass() does not exist on a non_object.

I am not sure why calling methods via GET is not enabled by default (security issue?) - I needed this for calls via jQuery. I fixed this by inserting this at line 191, into getHandler():

```
if($obj->hasMethod($relationName)) {
    $obj->$relationName();
    return null;
}
```

**Comment by maxime-rainville** [comment]
Unfortunately, [Silverstripe CMS 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for Silverstripe CMS 3 going forward.

You can read the [Silverstripe CMS Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.
