### ISSUE TITLE
canView() etc does not have member passed in as parameter

### ISSUE THREAD

**Issue by torleif** [silverstripe/silverstripe-restfulserver#19]
`canView ()`, `canDelete()`, and `canUpdate()` does not have the $member parameter passed in a variable. This means you can't have a DataObject with custom security options. 

This means you cannot authorise users.

**Comment by robbieaverill** [comment]
Hey @torleif

There's an assumption, and a policy in the core DataObjects, that if the member parameter for these methods is not passed then it will be gathered from `Member::currentUser()`.

I can totally understand that it shouldn't be assumed that this would happen in all cases, especially with custom DataObjects. I also don't see why we shouldn't pass this explicitly just in case.

I've opened a PR at #39 - would you be keen to test it out?

**Comment by torleif** [comment]
@robbieaverill: I gave it a test and it looks like it works as intended!

**Comment by dhensby** [comment]
fixed with #39
