### ISSUE TITLE
Separate RESTful and SOAP APIs in DataObject::$api_access

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-restfulserver#2]
Migrated from http://open.silverstripe.org/ticket/3727
$api_access = true is a bit simplistic, there should be a way to determine which API to enable. This is desireable to limit service exposure (attack surface) and general debugging for a specific implementation (most devs would gladly just support one API without worrying about implications of the other one).

**Comment by robbieaverill** [comment]
The `$api_access` static now accepts variable configuration options: https://github.com/silverstripe/silverstripe-restfulserver/tree/1.0.5#configuration

Closing - feel free to reopen if this is still affecting somebody.
