### ISSUE TITLE
Authentication will only work on missing DataObjects

### ISSUE THREAD

**Issue by torleif** [silverstripe/silverstripe-restfulserver#20]
restfulserver will only return a 401 if the DataObject does not exist. It seems related to issue #6, it causes authentication to fail depending on the server locale config. 

Also relating to issue #19, the user will not be able to be authorised if the authentication details are inaccessible.

**Comment by robbieaverill** [comment]
I've re-tested this and it's no longer an issue:

```php
class HomePage extends Page
{
    public function canView($member = null)
    {
        return Permission::check('ADMIN');
    }
}
```

HomePage with ID 1 exists, test to retrieve anonymously:

```
$ curl http://cwp17.dev/api/v1/HomePage/1.json -I
HTTP/1.1 401 Unauthorized
...
```

Result is 401 when the page exists ✅ 

HomePage with ID 2 does not exist, test to retrieve anonymously:

```
$ curl http://cwp17.dev/api/v1/HomePage/2.json -I
HTTP/1.1 404 Not Found
...
```

Result is 404 when the page does not exist ✅

**Comment by dhensby** [comment]
Shouldn't the API always return a 401 to prevent information disclosure? Then if the user is authenticated then they can get the 404.

**Comment by robbieaverill** [comment]
Yep, sounds like a good idea
