### ISSUE TITLE
Casting object for a field don't work

### ISSUE THREAD

**Issue by rchntrl** [silverstripe/silverstripe-restfulserver#22]
for example, I want to display field "CoverThumbnail"

``` php
Class Element extends DataObject {

    //...

    private static $casting = array(
        "CoverThumbnail" => "Varchar(255)"
    );

    public function getCoverThumbnail() {
        return  $this->CoverImage()->SetRatioSize(240, 370)->getURL();
    }
}
```

**Comment by tractorcow** [comment]
Change your casting from `Varchar(255)` to `Varchar`. The argument syntax is only supported for `$db`.

**Comment by tractorcow** [comment]
Actually, it might not be "unsupported" so much as "unnecessary" :P Try it anyway?

**Comment by tractorcow** [comment]
Also can you please attach how you are using this in your template?

Try:

```html
<% if CoverImage %>
   Thumbnail = $CoverThumbnail
<% else %>
   No CoverImage
<% end_if %>
```

**Comment by rchntrl** [comment]
If i add search parameter ?fields=CoverThumbnail,  it works.
Also it works If I do this
```php
Class Element extends DataObject {
 
    //...
    public static $api_access = array(
	'view' => array('CoverThumbnail')
);
    //...
}
```
but it displays only one field - CoverThumbnail. 

My Data Objects has very many fields, should I enumerate all fields in $api_access property in each class? I don't like such a decision and I don't want to think that it is the only right decision.

**Comment by dhensby** [comment]
you can do just `$api_access = true` I believe, but that'll open the whole object up

**Comment by robbieaverill** [comment]
Closing as this looks like a problem with implementation rather than a bug. @rchntrl feel free to reopen this issue if you disagree! Thanks 😄
