### ISSUE TITLE
API method calls via POST result in invalid HTTP response

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-restfulserver#3]
Migrated from http://open.silverstripe.org/ticket/5814

sapphire/api/RestfulServer.php function postHandler() when it dispatches to a method on the object generates invalid HTTP.

Around line 403 the code makes a call to $obj->$relation(), ignoring the result, then sets the response status code to 204 and returns true. The resulting HTTP stream has Content-Length of 1 and a body of "1", which is invalid for a 204 response and confuses most clients.

My local workaround is (excuse formatting, I don't know how trac butchers my input):

```php
$resp = $this->getResponse();
$resp->setStatusCode(200); // default response code
$result = $obj->$relation(); // can change response code

if(!$result) {
    $resp->setStatusCode(204); // if result is falsy, no response
    return ;
} else {
    return $result; // use 200 or code set by method
}
```

.. I'm not sure if this breaks any conventions on how method results are used elsewhere.

Semi-related: I'd like a way to call methods with GET /api/v1/(Classname)/(ID)/(relation) -- they could pull data out of $_GET / $_REQUEST. This is an easy change to getHandler() but I'm not sure if it's a bad idea.

**Comment by robbieaverill** [comment]
I'm going to close this due to inactivity and an assumption that the issue has been fixed since 2012. If this issue is still affecting people, please feel free to open a new issue/reopen this one.
