### ISSUE TITLE
Feature request: Token based authentication

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-restfulserver#34]
I personally don't like having basic authentication to protect an API.

This is a general feature request, open for discussion, for the suggestion of adding an extra Authenticator for token based authentication (I have a preference for the [Amazon hash signature style](http://docs.aws.amazon.com/AmazonS3/latest/dev/RESTAuthentication.html)!).

Requirements:
* Exist alongside `BasicRestfulAuthenticator`, not replace
* Be named `TokenRestfulAuthenticator`
* Admin configurable API token interface *attached to Users* where you would define:
 * API Token (auto-generated GUID?)
 * Private key (auto-generated GUID?)
 * Active (bool)
 * Description - text input for referencing which tokens are which in admin
* Requests should contain a unix timestamp from when it was generated so that the RestfulServer can enforce a time limit on the request (e.g. 60 seconds)
* Authentication should take the payload and:
 * Load the private key that corresponds with the public API token provided
 * Create its own hash signature of all the payload data (excluding the provided hash itself, but including the token and the timestamp)
 * Compare both the hash with the provided hash
 * Enforce the request time limit period

This would allow the restfulserver module to ship with a much more secure authentication method, which is relatively easy to use for clients.

An example client request might be:

```php
$private_key = 'yoursupersecretkey';
$request_data = array(
    'token' => 'yourpublicapitoken',
    'timestamp' => time(),
    'fields' => 'Title,URLSegment,Content'
);

// Generate the hash signature:
$request_data['checksum'] = hash_hmac('sha256', implode($request_data), $private_key);

// Make API request
```

Open for discussion!

**Comment by dhensby** [comment]
I've implemented this on another site it's possible out of the box, I believe, by adding your own authenticator.

**Comment by robbieaverill** [comment]
@dhensby not sure why I didn't get a notification of your comment- have just seen it!

Do you think it's worth shipping the alternative with the package as a disabled option?

**Comment by dhensby** [comment]
@robbieaverill unfortunately this kind of thing really depends on what you're trying to achieve.

When I implemented this there were applications and users and a user would have a token that could only be used with an application (which had a token too) - semi OAuth style.

I think having it as an add-on module would be best

**Comment by dhensby** [comment]
Also, I'm afraid I'm going to close this as the issue trackers aren't for feature requests :( sorry
