### ISSUE TITLE
POST requests return incorrect response code

### ISSUE THREAD

**Issue by phptek** [silverstripe/silverstripe-restfulserver#63]
If I issue an HTTP POST against an enabled datamodel-as-endpoint, and the resource does not exist, one is created and the module correctly scaffolds a 201 response. However, in `postHandler()` the logic attempts to address the spec for HTTP 201 responses and automatically redirect to the newly created resource at `/api/v1/My-Data-Model/<ID>.json` by the addition of a `Location` header. 

This has at least 3 issues that I can see:

1. If I wish to make exclusive use of `canCreate()` logic on my data-model, and not have `canView()` consulted _at all_, I cannot, other than to manually run `removeHeader('Location')` in my app's calling logic.
2. I can no longer assert that a 201 "Created" code is returned by the response. The 'Location' header effectively renders the response a hard-out 200. (I appreciate that this is technically correct, but AFAICT is only one way to respect the spec)
3. The data contained in the auto-returned response may be data/process heavy, something API consumers may not want for their system.

My suggestion is simple; to add an opt-out YML config option to skip the addition of the `Location` header, but where the default is to maintain current behaviour.

example:

```
        if ($this->config()->get('add_location_on_created')) {
            $urlSafeClassName = $this->sanitiseClassName(get_class($obj));
            $apiBase = $this->config()->api_base;
            $objHref = Director::absoluteURL($apiBase . "$urlSafeClassName/$obj->ID" . $type);
            $this->getResponse()->addHeader('Location', $objHref);
        }
```

**Comment by NightJar** [comment]
Thanks for reporting @phptek - I'm going to link this to some other related issues from the past;
#10 and #62 sound very similar and may provide some historical context.

From interest, what is the version you have installed?

**Comment by phptek** [comment]
Currently running off dev-master

**Comment by robbieaverill** [comment]
Fancy a pull request? 😄

**Comment by phptek** [comment]
@robbieaverill Done. See #64
