### ISSUE TITLE
New objects in postHandler() are not created using Injector

### ISSUE THREAD

**Issue by phptek** [silverstripe/silverstripe-restfulserver#65]
In `postHandler()` new objects are not created via `Injector` meaning that developers cannot  make use of dependency injection or any other facet of `Injector` for those objects "managed" by the module.

From:

```
        $obj = new $className();
```

To

```
        use SilverStripe\Core\Injector\Injector;
        ...
        $obj = Injector::inst()->create($className);
```

**Comment by robbieaverill** [comment]
Fixed in #68
