### ISSUE TITLE
RestfulServer::$api_base has no effect

### ISSUE THREAD

**Issue by nikrolls** [silverstripe/silverstripe-restfulserver#7]
The current version of RestfulServer has a protected static $api_base with the value of "api/v1", however this isn't actually being used. If you change it there is no affect on the API url, and if you search Silverstripe core's framework directory you find that "api/v1" and "api/v1/live" are still defined in the default routes.yml.

This could be fixed by overriding the routes in RestfulServer, but it'd be best to remove it from Silverstripe core as well or you get a server error if you try to access /api/v1/*.

**Comment by robbieaverill** [comment]
@nikrolls do you still experience this problem? I wonder whether in addition to configuring new routes for `api/v2/*` in your user code you could also re-route `api/v1/*` to a 404 handler to avoid this issue?
