### ISSUE TITLE
Permit modification of list data in GET requests, prior to response

### ISSUE THREAD

**Issue by phptek** [silverstripe/silverstripe-restfulserver#70]
At the moment, if developers wish to modify the underlying list returned in a response to a GET request, we need to use IoC via `Injector` and a sublcass, redeclare `getHandler()` as necessary complete with our data changes, and return that.

This is clumsy, because at the point at which we have access to the data, it has already been formatted , meaning we need to decompose back into an array (from JSON for e.g.) then back into JSON again. Much cleaner and IMO efficient would be to permit modification of the underlying data _prior_ to delivery.

This is how we're doing it now:

```
class CustomRestfulServer extends RestfulServer
{
    ...
   
    public function getHandler($className, $id, $relationName)
    {
        ....
        ....

        $handlerData = parent::getHandler($className, $id, $relationName);

        // Do some custom mods to `$handlerData` response
       
        ...

        return $handlerData;
}
```

Much better would be to allow `Extension` subclasses to modify the underlying list via a call to `extend()` in `RestfulServer::getHandler()`, something like this:

```
    protected function getHandler($className, $id, $relationName)
    {
        ...
        ...

        if ($obj instanceof SS_List) {
            $objs = ArrayList::create($obj->toArray());
            foreach ($objs as $obj) {
                if (!$obj->canView($this->getMember())) {
                    $objs->remove($obj);
                }
            }
           // Allow userland `DataExtension` to modify this list
            $this->extend('updateRestfulGetData', $objs);
            $responseFormatter->setTotalSize($objs->count());
            return $responseFormatter->convertDataObjectSet($objs, $fields);
        }

        $obj->update($data);
        $obj->write();

        return $obj;
    }
```

**Comment by robbieaverill** [comment]
Adding an extension point sounds like a good idea to me
