### ISSUE TITLE
Endpoint aliases for human readable endpoints

### ISSUE THREAD

**Issue by sanderha** [silverstripe/silverstripe-restfulserver#81]
I needed this in my project and thought it might be nice to have in the module.
We didnt like to have endpoints like this one:
`/NobrainerWeb-App-Tracks-Track`
So we added some code, so that you can map endpoints aliases for certain dataobjects to achieve an endpoint like `/tracks` instead of the above.

PR: #80

**Comment by ScopeyNZ** [comment]
Closed by #80. Thanks @sanderha!
