### ISSUE TITLE
PHP syntax incompatibility in resolveClassName function 

### ISSUE THREAD

**Issue by omoustaouda** [silverstripe/silverstripe-restfulserver#82]
Package: **silverstripe/restfulserver**
Version: **2.2.0**

Hello,

in this function
**`\SilverStripe\RestfulServer\RestfulServer::resolveClassName `**

```
    protected function resolveClassName(HTTPRequest $request): string
    {
        $className = $request->param('ClassName');
        $aliases = self::config()->get('endpoint_aliases');

        return $aliases[$className] ?? $this->unsanitiseClassName($className);
    }
```

the return type is specified. `: string`

This is raising a syntax parsing error in PHP 5.6
but the package is not preventing the usage of PHP 5.6.

I see that this is the only function having the return type specified,
would be safe to remove the return type here?
If yes I can open a 2-lines PR.

This would restore compatibility again with PHP 5.6.

P.S.
In the return statement the null coalescence operator is used too, 
again, is present only in this function.

# Pulls request 
* [ ] https://github.com/silverstripe/silverstripe-restfulserver/pull/83

**Comment by robbieaverill** [comment]
Yep, if that's the only occurrence of PHP 7 only syntax then we'd welcome a PR to remove it. While SilverStripe 4.5 onwards will require PHP 7, these satellite modules are currently designed to cater to multiple versions of SilverStripe framework. When the time comes that we will depend on a new feature in core which requires a version bump, we can then start adding new APIs that use PHP 7 syntax.

**Comment by maxime-rainville** [comment]
https://github.com/silverstripe/silverstripe-restfulserver/pull/83 will tweak what was done in #80 so it's PHP5 compatible, but I only did it because it was trivial to fix.

**Comment by omoustaouda** [comment]
Oh great!
I understand : )

Thank you all
